### ISSUE TITLE
[Feature Request]: adding `blacken-docs` to `pre-commit`

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8262]
### Feature Description

Adding this to `pre-commit` will blacken Python snippets in many `.md` files:

```yaml
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        args: [--line-length=79]
        types_or: [rst, markdown, tex]
        additional_dependencies: [black]
```

However, there are some parsing errors that stop its `.pre-commit` integration.  Is anyone willing to work through the parsing errors so we can add this to `pre-commit`?

### Reason

It will lead to blackened code snippets in `.md` files

### Value of Feature

`black`ened code increases readability and standardization

**Comment by Disiok** [comment]
ya would be nice!

**Comment by nerdai** [comment]
Adding to our "Request For Contributions" board.

**Comment by aaronjimv** [comment]
Hello. I tried to add to `.pre-commit-config.yaml`
```
  - repo: https://github.com/asottile/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.10.0]
```
And locally run `pre-commit` without problem, but when I made the PR the Run linter showed me many `parse error`

---
https://github.com/run-llama/llama_index/actions/runs/6735291463/job/18308123091
